### ISSUE TITLE
Problems to install

### ISSUE THREAD

**Issue by robson036** [Lunes-platform/install_node#15]
There's some error in script, when download Wallet Generator.

![image](https://user-images.githubusercontent.com/46539960/127211527-053c1907-bea9-466f-8730-4fe3d019d6e3.png)

Steps to reproduce:

1. Clone repo
2. cd install_node
3. git pull
4. sudo su
5. ./install_node.py
6. Follow the steps. When scripts downloads the wallet generator the error occurs.

**Comment by olivmath** [comment]
This problem has to do with your internet connection
