### ISSUE TITLE
Binding error

### ISSUE THREAD

**Issue by momole02** [Lunes-platform/install_node#7]
Hello.

I've installed the node and made all the configurations, but i have the following error : 
`2019-08-11 15:49:19,548 WARN  [main] i.n.u.i.MacAddressUtil - Failed to find a usable hardware address from the network interfaces; using random bytes: f9:2e:c7:01:95:b0:d0:88
2019-08-11 15:49:20,477 ERROR [ctor.default-dispatcher-3] akka.io.TcpListener - Bind failed for TCP channel on endpoint [/0.0.0.0:5555]
java.net.BindException: Address already in use
`

I have already checked the port 127.0.0.1:5555 with tools like nmap, netstat .
For example : `lsof -i:5555` gives an empty result.

I am stuck and i don't know what do to.

Thanks

**Comment by olivmath** [comment]
Hello, try now with new installer!
